condense_wildcard_suffixes = true
edition = "2021"
imports_granularity="Crate"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = false
reorder_imports = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
